version: '3'

tasks:
  default:
    cmds:
      - task --list

  build:
    cmds:
      - elm make src/Main.elm
    sources:
      - elm.json
      - src/*.elm
      - src/**/*.elm
    generates:
      - index.html

    ignore_error: true

  build-prod:
    cmds:
      - elm make --optimize src/Main.elm
    sources:
      - elm.json
      - src/*.elm
      - src/**/*.elm
    generates:
      - index.html

    ignore_error: true
